const configData = {
    questions: {
      mathe: [
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 }

      ],

      deutsch: [
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 }

      ],

      englisch: [
  { question: "What is the correct form: I (go) to the store yesterday.", answers: ["went", "goes", "going"], correct: 0 },
  { question: "Choose the correct sentence: He (study) English every day.", answers: ["He study English every day.", "He studies English every day.", "He studied English every day."], correct: 1 },
  { question: "Which one is the synonym of 'happy'?", answers: ["sad", "joyful", "angry"], correct: 1 },
  { question: "Choose the correct sentence: She (read) a book when I called her.", answers: ["She reads a book when I called her.", "She read a book when I called her.", "She was reading a book when I called her."], correct: 2 },
  { question: "Fill in the blank: They arrived ______ 8 o'clock.", answers: ["on", "at", "in"], correct: 1 },
  { question: "What is the plural of 'child'?", answers: ["children", "childs", "childes"], correct: 0 },
  { question: "Which is the correct form: He (never/see) a movie like that before.", answers: ["never saw", "has never seen", "never seen"], correct: 1 },
  { question: "Choose the correct sentence: I (be) to Paris last summer.", answers: ["I were to Paris last summer.", "I am to Paris last summer.", "I was to Paris last summer."], correct: 2 },
  { question: "Fill in the blank: We haven't seen her ______ last week.", answers: ["since", "for", "on"], correct: 0 },
  { question: "Which one is correct? I (not/understand) the question.", answers: ["I don't understand the question.", "I doesn't understand the question.", "I not understand the question."], correct: 0 },
  { question: "What is the opposite of 'old'?", answers: ["young", "new", "modern"], correct: 1 },
  { question: "Fill in the blank: I will wait ______ the bus stop.", answers: ["at", "on", "in"], correct: 0 },
  { question: "Which sentence is correct?", answers: ["I have meet her before.", "I met her before.", "I have met her before."], correct: 2 },
  { question: "What is the correct form: They (live) in this city for 10 years.", answers: ["They lived in this city for 10 years.", "They have lived in this city for 10 years.", "They live in this city for 10 years."], correct: 1 },
  { question: "Fill in the blank: She is the (smart) student in the class.", answers: ["smarter", "smartest", "more smart"], correct: 1 },
  { question: "Choose the correct form: I (finish) my homework when you called.", answers: ["I finish my homework when you called.", "I finished my homework when you called.", "I had finished my homework when you called."], correct: 2 },
  { question: "What is the past tense of 'run'?", answers: ["runned", "ran", "run"], correct: 1 },
  { question: "Which one is the correct word? He is always (late) for class.", answers: ["lateness", "late", "lates"], correct: 1 },
  { question: "Fill in the blank: We will go to the cinema ______ it stops raining.", answers: ["until", "before", "after"], correct: 2 },
  { question: "What is the opposite of 'hot'?", answers: ["cold", "warm", "cool"], correct: 0 },
  { question: "What is the correct plural form of 'goose'?", answers: ["gooses", "geese", "goosees"], correct: 1 },
  { question: "Fill in the blank: I have been working here ______ two years.", answers: ["for", "since", "during"], correct: 0 },
  { question: "What is the synonym of 'difficult'?", answers: ["easy", "hard", "simple"], correct: 1 },
  { question: "Which of the following is correct? I have seen him (yesterday).", answers: ["I have seen him yesterday.", "I seen him yesterday.", "I saw him yesterday."], correct: 2 },
  { question: "What is the correct sentence?", answers: ["She don't like coffee.", "She doesn't like coffee.", "She doesn't likes coffee."], correct: 1 },
  { question: "Fill in the blank: I will call you when I (arrive) home.", answers: ["arrived", "arriving", "arrives"], correct: 2 },
  { question: "Choose the correct question form: (you/go) to the party last weekend?", answers: ["Did you went to the party last weekend?", "Do you went to the party last weekend?", "Did you go to the party last weekend?"], correct: 2 },
  { question: "Which one is correct?", answers: ["She is more taller than me.", "She is the most taller than me.", "She is taller than me."], correct: 2 },
  { question: "What is the opposite of 'light'?", answers: ["heavy", "dark", "bright"], correct: 0 }
      ]
    }
  };


