const configData = {
    questions: {
      mathe: [
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 }

      ],

      deutsch: [
        { question: "Aktiv oder Passiv Satz mnbvbnnbcghvnghjcfghjvfz8iu zinswers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 }

      ],

      englisch: [
        { question: "Wie lautet have in simple past?", answers: ["had", "have", "hod"], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },
        { question: "", answers: ["", "", ""], correct: 0 },

      ]
    }
  };